osx_image: xcode10
language: swift
script:
  - pod install --project-directory=Examples
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Examples/SimpleSourceExample.xcworkspace -scheme SimpleSource-Unit-Tests -destination 'name=iPhone 8' ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'SimpleSource'