platform :ios, '13.0'

target 'SimpleSourceExample' do
    use_frameworks!

    pod 'SimpleSource', :path => '..', :testspecs => ['Tests']
    pod 'SwiftyJSON'
end

def inherit_project_deployment_target(installer)
  ios_min_deployment_target = "13.0"
  puts "Bumping pods iOS deployment target to the minimal available (#{ios_min_deployment_target})"
  installer.pods_project.targets.each do |target|
    if target.platform_name == :ios && target.deployment_target.to_f < ios_min_deployment_target.to_f
      puts "\t#{target.name} has iOS deployment target set to #{target.deployment_target}. Bumping to #{ios_min_deployment_target}"
      target.deployment_target = ios_min_deployment_target
    end
  end
end

post_install do |installer|
  inherit_project_deployment_target(installer)
end
